version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
    restart: always